### ISSUE TITLE
Please remove jQuery from bower

### ISSUE THREAD

**Issue by anhtran** [simison/angular-mailcheck#1]
I don't see that you were using jQuery inside the code. Why did you put it in the requirements?

-- Update: Sorry, I didn't read the reqs of mailcheck!

**Comment by simison** [comment]
Actually, I'm not sure if Mailcheck really requires jQuery and if it does, Bower should check its requirements and then fetch jQuery (angular-mailcheck -> mailcheck -> jquery).

This script also relies on  jQuery, [here](https://github.com/simison/angular-mailcheck/blob/145e52dcfe329431b2c8b2ad9234ee077cdb79a5/angular-mailcheck.js#L53).

I think it could be replaced with something like this:

``` javascript
element[0].parentNode.insertBefore(template[0], element[0].nextSibling);
```

...if you have time, feel free to edit+test+PR. :-)

I'll check this at some point myself when I find a nice slot of spare time. Leaving this open as a reminder.

**Comment by anhtran** [comment]
Thank you for the response. Mailcheck.js is great but when I found out that it relies on jQuery, I have a little bit disappointed. I was hoping it's something indie like `moment.js` or `underscore.js`.

**Comment by simison** [comment]
I removed dependency from this package.
