### ISSUE TITLE
How to pass variables to mailcheck?

### ISSUE THREAD

**Issue by brunomperes** [simison/angular-mailcheck#4]
How can I pass variables such as domains & secondLevelDomains to mailcheck?

**Comment by simison** [comment]
Mailcheck has all these options:
```js
  {
    domains: domains,                       // optional
    secondLevelDomains: secondLevelDomains, // optional
    topLevelDomains: topLevelDomains,       // optional
    distanceFunction: superStringDistance,  // optional
    suggested: function(element, suggestion) {
      // callback code
    },
    empty: function(element) {
      // callback code
    }
  }
```

...and [we're passing](https://github.com/simison/angular-mailcheck/blob/master/angular-mailcheck.js#L60-L66) only `suggested` and `empty` for Mailcheck.

I'd imagine most flexible and future proof way would to be able to pass settings object which then would be combined using [`angular.extend`](https://docs.angularjs.org/api/ng/function/angular.extend) with our `suggested` and `empty` functions.

As always, PRs welcome!

**Comment by simison** [comment]
Added possibility to pass options object:

https://github.com/simison/angular-mailcheck/commit/408acdf299549115afdb6617ccf1c09e5f6136bb
